[build]
  command = "hugo"
  publish = "public"

  [[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self' https://localhost:3000"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

